/*
 * This file is part of the GridXSLT project
 * Copyright (C) 2005 Peter Kelly (pmk@cs.adelaide.edu.au)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * $Id$
 *
 */

/*

  @implements(xpath-functions:durations-dates-times-1) status { deferred } @end
  @implements(xpath-functions:date-time-values-1) status { deferred } @end
  @implements(xpath-functions:d1e3810-1) status { deferred } @end
  @implements(xpath-functions:d1e3828-1) status { deferred } @end
  @implements(xpath-functions:d1e3828-2) status { deferred } @end
  @implements(xpath-functions:d1e3828-3) status { deferred } @end
  @implements(xpath-functions:d1e3828-4) status { deferred } @end
  @implements(xpath-functions:d1e3828-5) status { deferred } @end
  @implements(xpath-functions:d1e3828-6) status { deferred } @end
  @implements(xpath-functions:date-time-duration-conformance-1) status { deferred } @end
  @implements(xpath-functions:date-time-duration-conformance-2) status { deferred } @end
  @implements(xpath-functions:date-time-duration-conformance-3) status { deferred } @end
  @implements(xpath-functions:date-time-duration-conformance-4) status { deferred } @end
  @implements(xpath-functions:duration-subtypes-1) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-1) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-2) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-3) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-4) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-5) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-6) status { deferred } @end
  @implements(xpath-functions:dt-yearMonthDuration-7) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-5) status { deferred } @end
  @implements(xpath-functions:dt-dayTimeDuration-6) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-1) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-2) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-3) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-4) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-5) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-6) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-7) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-8) status { deferred } @end
  @implements(xpath-functions:comp.duration.datetime-9) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-equal-1) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-equal-2) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-equal-3) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-less-than-1) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-less-than-2) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-less-than-3) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-greater-than-1) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-greater-than-2) status { deferred } @end
  @implements(xpath-functions:func-yearMonthDuration-greater-than-3) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-equal-1) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-equal-2) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-equal-3) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-less-than-1) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-less-than-2) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-less-than-3) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-greater-than-1) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-greater-than-2) status { deferred } @end
  @implements(xpath-functions:func-dayTimeDuration-greater-than-3) status { deferred } @end
  @implements(xpath-functions:func-dateTime-equal-1) status { deferred } @end
  @implements(xpath-functions:func-dateTime-equal-2) status { deferred } @end
  @implements(xpath-functions:func-dateTime-equal-3) status { deferred } @end
  @implements(xpath-functions:func-dateTime-equal-4) status { deferred } @end
  @implements(xpath-functions:func-dateTime-less-than-1) status { deferred } @end
  @implements(xpath-functions:func-dateTime-less-than-2) status { deferred } @end
  @implements(xpath-functions:func-dateTime-less-than-3) status { deferred } @end
  @implements(xpath-functions:func-dateTime-greater-than-1) status { deferred } @end
  @implements(xpath-functions:func-dateTime-greater-than-2) status { deferred } @end
  @implements(xpath-functions:func-dateTime-greater-than-3) status { deferred } @end
  @implements(xpath-functions:func-date-equal-1) status { deferred } @end
  @implements(xpath-functions:func-date-equal-2) status { deferred } @end
  @implements(xpath-functions:func-date-equal-3) status { deferred } @end
  @implements(xpath-functions:func-date-equal-4) status { deferred } @end
  @implements(xpath-functions:func-date-equal-5) status { deferred } @end
  @implements(xpath-functions:func-date-equal-6) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-1) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-2) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-3) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-4) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-5) status { deferred } @end
  @implements(xpath-functions:func-date-less-than-6) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-1) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-2) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-3) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-4) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-5) status { deferred } @end
  @implements(xpath-functions:func-date-greater-than-6) status { deferred } @end
  @implements(xpath-functions:func-time-equal-1) status { deferred } @end
  @implements(xpath-functions:func-time-equal-2) status { deferred } @end
  @implements(xpath-functions:func-time-equal-3) status { deferred } @end
  @implements(xpath-functions:func-time-equal-4) status { deferred } @end
  @implements(xpath-functions:func-time-equal-5) status { deferred } @end
  @implements(xpath-functions:func-time-less-than-1) status { deferred } @end
  @implements(xpath-functions:func-time-less-than-2) status { deferred } @end
  @implements(xpath-functions:func-time-less-than-3) status { deferred } @end
  @implements(xpath-functions:func-time-less-than-4) status { deferred } @end
  @implements(xpath-functions:func-time-less-than-5) status { deferred } @end
  @implements(xpath-functions:func-time-greater-than-1) status { deferred } @end
  @implements(xpath-functions:func-time-greater-than-2) status { deferred } @end
  @implements(xpath-functions:func-time-greater-than-3) status { deferred } @end
  @implements(xpath-functions:func-time-greater-than-4) status { deferred } @end
  @implements(xpath-functions:func-time-greater-than-5) status { deferred } @end
  @implements(xpath-functions:func-gYearMonth-equal-1) status { deferred } @end
  @implements(xpath-functions:func-gYearMonth-equal-2) status { deferred } @end
  @implements(xpath-functions:func-gYearMonth-equal-3) status { deferred } @end
  @implements(xpath-functions:func-gYearMonth-equal-4) status { deferred } @end
  @implements(xpath-functions:func-gYearMonth-equal-5) status { deferred } @end
  @implements(xpath-functions:func-gYear-equal-1) status { deferred } @end
  @implements(xpath-functions:func-gYear-equal-2) status { deferred } @end
  @implements(xpath-functions:func-gYear-equal-3) status { deferred } @end
  @implements(xpath-functions:func-gYear-equal-4) status { deferred } @end
  @implements(xpath-functions:func-gYear-equal-5) status { deferred } @end
  @implements(xpath-functions:func-gMonthDay-equal-1) status { deferred } @end
  @implements(xpath-functions:func-gMonthDay-equal-2) status { deferred } @end
  @implements(xpath-functions:func-gMonthDay-equal-3) status { deferred } @end
  @implements(xpath-functions:func-gMonthDay-equal-4) status { deferred } @end
  @implements(xpath-functions:func-gMonthDay-equal-5) status { deferred } @end
  @implements(xpath-functions:func-gMonth-equal-1) status { deferred } @end
  @implements(xpath-functions:func-gMonth-equal-2) status { deferred } @end
  @implements(xpath-functions:func-gMonth-equal-3) status { deferred } @end
  @implements(xpath-functions:func-gMonth-equal-4) status { deferred } @end
  @implements(xpath-functions:func-gMonth-equal-5) status { deferred } @end
  @implements(xpath-functions:func-gDay-equal-1) status { deferred } @end
  @implements(xpath-functions:func-gDay-equal-2) status { deferred } @end
  @implements(xpath-functions:func-gDay-equal-3) status { deferred } @end
  @implements(xpath-functions:func-gDay-equal-4) status { deferred } @end
  @implements(xpath-functions:func-gDay-equal-5) status { deferred } @end
  @implements(xpath-functions:d1e4771-1) status { deferred } @end
  @implements(xpath-functions:d1e4771-2) status { deferred } @end
  @implements(xpath-functions:func-years-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-years-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-years-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-years-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-months-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-months-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-months-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-months-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-days-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-days-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-days-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-days-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-hours-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-hours-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-hours-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-hours-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-duration-1) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-duration-2) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-duration-3) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-duration-4) status { deferred } @end
  @implements(xpath-functions:func-year-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-year-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-year-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-year-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-month-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-month-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-month-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-month-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-day-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-day-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-day-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-day-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-hours-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-hours-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-hours-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-hours-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-year-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-year-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-year-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-year-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-month-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-month-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-month-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-month-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-day-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-day-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-day-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-day-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-hours-from-time-1) status { deferred } @end
  @implements(xpath-functions:func-hours-from-time-2) status { deferred } @end
  @implements(xpath-functions:func-hours-from-time-3) status { deferred } @end
  @implements(xpath-functions:func-hours-from-time-4) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-time-1) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-time-2) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-time-3) status { deferred } @end
  @implements(xpath-functions:func-minutes-from-time-4) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-time-1) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-time-2) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-time-3) status { deferred } @end
  @implements(xpath-functions:func-seconds-from-time-4) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-time-1) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-time-2) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-time-3) status { deferred } @end
  @implements(xpath-functions:func-timezone-from-time-4) status { deferred } @end
  @implements(xpath-functions:duration-arithmetic-1) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDurations-1) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDurations-2) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDurations-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDurations-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDurations-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDurations-3) status { deferred } @end
  @implements(xpath-functions:func-multiply-yearMonthDuration-1) status { deferred } @end
  @implements(xpath-functions:func-multiply-yearMonthDuration-2) status { deferred } @end
  @implements(xpath-functions:func-multiply-yearMonthDuration-3) status { deferred } @end
  @implements(xpath-functions:func-multiply-yearMonthDuration-4) status { deferred } @end
  @implements(xpath-functions:func-multiply-yearMonthDuration-5) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-1) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-2) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-3) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-4) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-5) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-by-yearMonthDuration-1) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-by-yearMonthDuration-2) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-by-yearMonthDuration-3) status { deferred } @end
  @implements(xpath-functions:func-divide-yearMonthDuration-by-yearMonthDuration-4) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDurations-1) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDurations-2) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDurations-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDurations-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDurations-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDurations-3) status { deferred } @end
  @implements(xpath-functions:func-multiply-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:func-multiply-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:func-multiply-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:func-multiply-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:func-multiply-dayTimeDuration-5) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-5) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-by-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-by-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-by-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:func-divide-dayTimeDuration-by-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:timezone.functions-1) status { deferred } @end
  @implements(xpath-functions:timezone.functions-2) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-1) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-2) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-3) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-4) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-5) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-6) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-7) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-8) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-9) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-10) status { deferred } @end
  @implements(xpath-functions:func-adjust-dateTime-to-timezone-11) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-1) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-2) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-3) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-4) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-5) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-6) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-7) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-8) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-9) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-10) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-11) status { deferred } @end
  @implements(xpath-functions:func-adjust-date-to-timezone-12) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-1) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-2) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-3) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-4) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-5) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-6) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-7) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-8) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-9) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-10) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-11) status { deferred } @end
  @implements(xpath-functions:func-adjust-time-to-timezone-12) status { deferred } @end
  @implements(xpath-functions:dateTime-arithmetic-1) status { deferred } @end
  @implements(xpath-functions:dateTime-arithmetic-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dateTimes-yielding-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dateTimes-yielding-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dateTimes-yielding-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dateTimes-yielding-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-dateTimes-yielding-dayTimeDuration-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-6) status { deferred } @end
  @implements(xpath-functions:func-subtract-dates-yielding-dayTimeDuration-7) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-times-6) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-dateTime-5) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-dateTime-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-dateTime-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-dateTime-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-dateTime-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-dateTime-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-dateTime-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-dateTime-5) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-1) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-2) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-3) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-4) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-5) status { deferred } @end
  @implements(xpath-functions:func-add-yearMonthDuration-to-date-6) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-1) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-2) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-3) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-4) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-5) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-date-6) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-yearMonthDuration-from-date-6) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-date-6) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-time-1) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-time-2) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-time-3) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-time-4) status { deferred } @end
  @implements(xpath-functions:func-add-dayTimeDuration-to-time-5) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-time-1) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-time-2) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-time-3) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-time-4) status { deferred } @end
  @implements(xpath-functions:func-subtract-dayTimeDuration-from-time-5) status { deferred } @end

  @implements(xpath-functions:examples-1) status { info } @end
  @implements(xpath-functions:examples-2) status { info } @end
  @implements(xpath-functions:examples-3) status { info } @end
  @implements(xpath-functions:if-empty-if-absent-1) status { info } @end
  @implements(xpath-functions:if-empty-1) status { info } @end
  @implements(xpath-functions:if-empty-2) status { info } @end
  @implements(xpath-functions:if-empty-3) status { info } @end
  @implements(xpath-functions:if-empty-4) status { info } @end
  @implements(xpath-functions:if-empty-5) status { info } @end
  @implements(xpath-functions:if-empty-6) status { info } @end
  @implements(xpath-functions:if-absent-1) status { info } @end
  @implements(xpath-functions:if-absent-2) status { info } @end
  @implements(xpath-functions:if-absent-3) status { info } @end
  @implements(xpath-functions:if-absent-4) status { info } @end
  @implements(xpath-functions:if-absent-5) status { info } @end
  @implements(xpath-functions:if-absent-6) status { info } @end
  @implements(xpath-functions:value-union-1) status { info } @end
  @implements(xpath-functions:value-union-2) status { info } @end
  @implements(xpath-functions:value-union-3) status { info } @end
  @implements(xpath-functions:value-union-4) status { info } @end
  @implements(xpath-functions:value-union-5) status { info } @end
  @implements(xpath-functions:value-union-6) status { info } @end
  @implements(xpath-functions:value-intersect-1) status { info } @end
  @implements(xpath-functions:value-intersect-2) status { info } @end
  @implements(xpath-functions:value-intersect-3) status { info } @end
  @implements(xpath-functions:value-intersect-4) status { info } @end
  @implements(xpath-functions:value-intersect-5) status { info } @end
  @implements(xpath-functions:value-intersect-6) status { info } @end
  @implements(xpath-functions:value-except-1) status { info } @end
  @implements(xpath-functions:value-except-2) status { info } @end
  @implements(xpath-functions:value-except-3) status { info } @end
  @implements(xpath-functions:value-except-4) status { info } @end
  @implements(xpath-functions:value-except-5) status { info } @end
  @implements(xpath-functions:value-except-6) status { info } @end
  @implements(xpath-functions:index-of-node-1) status { info } @end
  @implements(xpath-functions:index-of-node-2) status { info } @end
  @implements(xpath-functions:index-of-node-3) status { info } @end
  @implements(xpath-functions:index-of-node-4) status { info } @end
  @implements(xpath-functions:index-of-node-5) status { info } @end
  @implements(xpath-functions:index-of-node-6) status { info } @end
  @implements(xpath-functions:index-of-node-7) status { info } @end
  @implements(xpath-functions:index-of-node-8) status { info } @end
  @implements(xpath-functions:index-of-node-9) status { info } @end
  @implements(xpath-functions:index-of-node-10) status { info } @end
  @implements(xpath-functions:string-pad-1) status { info } @end
  @implements(xpath-functions:string-pad-2) status { info } @end
  @implements(xpath-functions:string-pad-3) status { info } @end
  @implements(xpath-functions:string-pad-4) status { info } @end
  @implements(xpath-functions:string-pad-5) status { info } @end
  @implements(xpath-functions:string-pad-6) status { info } @end
  @implements(xpath-functions:string-pad-7) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-1) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-2) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-3) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-4) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-5) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-6) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-7) status { info } @end
  @implements(xpath-functions:func-distinct-nodes-stable-8) status { info } @end
  @implements(xpath-functions:working-with-duration-values-1) status { info } @end
  @implements(xpath-functions:working-with-duration-values-2) status { info } @end
  @implements(xpath-functions:working-with-duration-values-3) status { info } @end
  @implements(xpath-functions:working-with-duration-values-4) status { info } @end
  @implements(xpath-functions:working-with-duration-values-5) status { info } @end
  @implements(xpath-functions:working-with-duration-values-6) status { info } @end


  @implements(xpath-functions:normative-biblio-1) status { info } @end
  @implements(xpath-functions:non-normative-biblio-1) status { info } @end

  @implements(xpath-functions:quickref-section-1) status { info } @end

  @implements(xpath-functions:quickref-alpha-1) status { info } @end
  @implements(xpath-functions:quickref-alpha-2) status { info } @end
  @implements(xpath-functions:quickref-alpha-3) status { info } @end
  @implements(xpath-functions:quickref-alpha-4) status { info } @end
  @implements(xpath-functions:quickref-alpha-5) status { info } @end
  @implements(xpath-functions:quickref-alpha-6) status { info } @end
  @implements(xpath-functions:quickref-alpha-7) status { info } @end
  @implements(xpath-functions:quickref-alpha-8) status { info } @end
  @implements(xpath-functions:quickref-alpha-9) status { info } @end
  @implements(xpath-functions:quickref-alpha-10) status { info } @end
  @implements(xpath-functions:quickref-alpha-11) status { info } @end
  @implements(xpath-functions:quickref-alpha-12) status { info } @end
  @implements(xpath-functions:quickref-alpha-13) status { info } @end
  @implements(xpath-functions:quickref-alpha-14) status { info } @end
  @implements(xpath-functions:quickref-alpha-15) status { info } @end
  @implements(xpath-functions:quickref-alpha-16) status { info } @end
  @implements(xpath-functions:quickref-alpha-17) status { info } @end
  @implements(xpath-functions:quickref-alpha-18) status { info } @end
  @implements(xpath-functions:quickref-alpha-19) status { info } @end
  @implements(xpath-functions:quickref-alpha-20) status { info } @end
  @implements(xpath-functions:quickref-alpha-21) status { info } @end
  @implements(xpath-functions:quickref-alpha-22) status { info } @end
  @implements(xpath-functions:quickref-alpha-23) status { info } @end
  @implements(xpath-functions:quickref-alpha-24) status { info } @end
  @implements(xpath-functions:quickref-alpha-25) status { info } @end
  @implements(xpath-functions:quickref-alpha-26) status { info } @end
  @implements(xpath-functions:quickref-alpha-27) status { info } @end
  @implements(xpath-functions:quickref-alpha-28) status { info } @end
  @implements(xpath-functions:quickref-alpha-29) status { info } @end
  @implements(xpath-functions:quickref-alpha-30) status { info } @end
  @implements(xpath-functions:quickref-alpha-31) status { info } @end
  @implements(xpath-functions:quickref-alpha-32) status { info } @end
  @implements(xpath-functions:quickref-alpha-33) status { info } @end
  @implements(xpath-functions:quickref-alpha-34) status { info } @end
  @implements(xpath-functions:quickref-alpha-35) status { info } @end
  @implements(xpath-functions:quickref-alpha-36) status { info } @end
  @implements(xpath-functions:quickref-alpha-37) status { info } @end
  @implements(xpath-functions:quickref-alpha-38) status { info } @end
  @implements(xpath-functions:quickref-alpha-39) status { info } @end
  @implements(xpath-functions:quickref-alpha-40) status { info } @end
  @implements(xpath-functions:quickref-alpha-41) status { info } @end
  @implements(xpath-functions:quickref-alpha-42) status { info } @end
  @implements(xpath-functions:quickref-alpha-43) status { info } @end
  @implements(xpath-functions:quickref-alpha-44) status { info } @end
  @implements(xpath-functions:quickref-alpha-45) status { info } @end
  @implements(xpath-functions:quickref-alpha-46) status { info } @end
  @implements(xpath-functions:quickref-alpha-47) status { info } @end
  @implements(xpath-functions:quickref-alpha-48) status { info } @end
  @implements(xpath-functions:quickref-alpha-49) status { info } @end
  @implements(xpath-functions:quickref-alpha-50) status { info } @end
  @implements(xpath-functions:quickref-alpha-51) status { info } @end
  @implements(xpath-functions:quickref-alpha-52) status { info } @end
  @implements(xpath-functions:quickref-alpha-53) status { info } @end
  @implements(xpath-functions:quickref-alpha-54) status { info } @end
  @implements(xpath-functions:quickref-alpha-55) status { info } @end
  @implements(xpath-functions:quickref-alpha-56) status { info } @end
  @implements(xpath-functions:quickref-alpha-57) status { info } @end
  @implements(xpath-functions:quickref-alpha-58) status { info } @end
  @implements(xpath-functions:quickref-alpha-59) status { info } @end
  @implements(xpath-functions:quickref-alpha-60) status { info } @end
  @implements(xpath-functions:quickref-alpha-61) status { info } @end
  @implements(xpath-functions:quickref-alpha-62) status { info } @end
  @implements(xpath-functions:quickref-alpha-63) status { info } @end
  @implements(xpath-functions:quickref-alpha-64) status { info } @end
  @implements(xpath-functions:quickref-alpha-65) status { info } @end
  @implements(xpath-functions:quickref-alpha-66) status { info } @end
  @implements(xpath-functions:quickref-alpha-67) status { info } @end
  @implements(xpath-functions:quickref-alpha-68) status { info } @end
  @implements(xpath-functions:quickref-alpha-69) status { info } @end
  @implements(xpath-functions:quickref-alpha-70) status { info } @end
  @implements(xpath-functions:quickref-alpha-71) status { info } @end
  @implements(xpath-functions:quickref-alpha-72) status { info } @end
  @implements(xpath-functions:quickref-alpha-73) status { info } @end
  @implements(xpath-functions:quickref-alpha-74) status { info } @end
  @implements(xpath-functions:quickref-alpha-75) status { info } @end
  @implements(xpath-functions:quickref-alpha-76) status { info } @end
  @implements(xpath-functions:quickref-alpha-77) status { info } @end
  @implements(xpath-functions:quickref-alpha-78) status { info } @end
  @implements(xpath-functions:quickref-alpha-79) status { info } @end
  @implements(xpath-functions:quickref-alpha-80) status { info } @end
  @implements(xpath-functions:quickref-alpha-81) status { info } @end
  @implements(xpath-functions:quickref-alpha-82) status { info } @end
  @implements(xpath-functions:quickref-alpha-83) status { info } @end
  @implements(xpath-functions:quickref-alpha-84) status { info } @end
  @implements(xpath-functions:quickref-alpha-85) status { info } @end
  @implements(xpath-functions:quickref-alpha-86) status { info } @end
  @implements(xpath-functions:quickref-alpha-87) status { info } @end
  @implements(xpath-functions:quickref-alpha-88) status { info } @end
  @implements(xpath-functions:quickref-alpha-89) status { info } @end
  @implements(xpath-functions:quickref-alpha-90) status { info } @end
  @implements(xpath-functions:quickref-alpha-91) status { info } @end
  @implements(xpath-functions:quickref-alpha-92) status { info } @end
  @implements(xpath-functions:quickref-alpha-93) status { info } @end
  @implements(xpath-functions:quickref-alpha-94) status { info } @end
  @implements(xpath-functions:quickref-alpha-95) status { info } @end
  @implements(xpath-functions:quickref-alpha-96) status { info } @end
  @implements(xpath-functions:quickref-alpha-97) status { info } @end
  @implements(xpath-functions:quickref-alpha-98) status { info } @end
  @implements(xpath-functions:quickref-alpha-99) status { info } @end
  @implements(xpath-functions:quickref-alpha-100) status { info } @end
  @implements(xpath-functions:quickref-alpha-101) status { info } @end
  @implements(xpath-functions:quickref-alpha-102) status { info } @end
  @implements(xpath-functions:quickref-alpha-103) status { info } @end
  @implements(xpath-functions:quickref-alpha-104) status { info } @end
  @implements(xpath-functions:quickref-alpha-105) status { info } @end
  @implements(xpath-functions:quickref-alpha-106) status { info } @end
  @implements(xpath-functions:quickref-alpha-107) status { info } @end
  @implements(xpath-functions:quickref-alpha-108) status { info } @end
  @implements(xpath-functions:quickref-alpha-109) status { info } @end
  @implements(xpath-functions:quickref-alpha-110) status { info } @end
  @implements(xpath-functions:quickref-alpha-111) status { info } @end
  @implements(xpath-functions:quickref-alpha-112) status { info } @end
  @implements(xpath-functions:quickref-alpha-113) status { info } @end
  @implements(xpath-functions:quickref-alpha-114) status { info } @end
  @implements(xpath-functions:quickref-alpha-115) status { info } @end
  @implements(xpath-functions:quickref-alpha-116) status { info } @end
  @implements(xpath-functions:quickref-alpha-117) status { info } @end
  @implements(xpath-functions:quickref-alpha-118) status { info } @end
  @implements(xpath-functions:quickref-alpha-119) status { info } @end
  @implements(xpath-functions:quickref-alpha-120) status { info } @end
  @implements(xpath-functions:quickref-alpha-121) status { info } @end
  @implements(xpath-functions:quickref-alpha-122) status { info } @end
  @implements(xpath-functions:quickref-alpha-123) status { info } @end
  @implements(xpath-functions:quickref-alpha-124) status { info } @end
  @implements(xpath-functions:quickref-alpha-125) status { info } @end
  @implements(xpath-functions:quickref-alpha-126) status { info } @end
  @implements(xpath-functions:quickref-alpha-127) status { info } @end
  @implements(xpath-functions:quickref-alpha-128) status { info } @end
  @implements(xpath-functions:quickref-alpha-129) status { info } @end
  @implements(xpath-functions:quickref-alpha-130) status { info } @end
  @implements(xpath-functions:quickref-alpha-131) status { info } @end
  @implements(xpath-functions:quickref-alpha-132) status { info } @end
  @implements(xpath-functions:quickref-alpha-133) status { info } @end
  @implements(xpath-functions:quickref-alpha-134) status { info } @end
  @implements(xpath-functions:quickref-alpha-135) status { info } @end
  @implements(xpath-functions:quickref-alpha-136) status { info } @end
  @implements(xpath-functions:quickref-alpha-137) status { info } @end
  @implements(xpath-functions:quickref-alpha-138) status { info } @end
  @implements(xpath-functions:quickref-alpha-139) status { info } @end
  @implements(xpath-functions:quickref-alpha-140) status { info } @end
  @implements(xpath-functions:quickref-alpha-141) status { info } @end
  @implements(xpath-functions:quickref-alpha-142) status { info } @end
  @implements(xpath-functions:quickref-alpha-143) status { info } @end
  @implements(xpath-functions:quickref-alpha-144) status { info } @end
  @implements(xpath-functions:quickref-alpha-145) status { info } @end
  @implements(xpath-functions:quickref-alpha-146) status { info } @end
  @implements(xpath-functions:quickref-alpha-147) status { info } @end
  @implements(xpath-functions:quickref-alpha-148) status { info } @end
  @implements(xpath-functions:quickref-alpha-149) status { info } @end
  @implements(xpath-functions:quickref-alpha-150) status { info } @end
  @implements(xpath-functions:quickref-alpha-151) status { info } @end
  @implements(xpath-functions:quickref-alpha-152) status { info } @end
  @implements(xpath-functions:quickref-alpha-153) status { info } @end
  @implements(xpath-functions:quickref-alpha-154) status { info } @end
  @implements(xpath-functions:quickref-alpha-155) status { info } @end
  @implements(xpath-functions:quickref-alpha-156) status { info } @end
  @implements(xpath-functions:quickref-alpha-157) status { info } @end
  @implements(xpath-functions:quickref-alpha-158) status { info } @end
  @implements(xpath-functions:quickref-alpha-159) status { info } @end
  @implements(xpath-functions:quickref-alpha-160) status { info } @end
  @implements(xpath-functions:quickref-alpha-161) status { info } @end
  @implements(xpath-functions:quickref-alpha-162) status { info } @end
  @implements(xpath-functions:quickref-alpha-163) status { info } @end
  @implements(xpath-functions:quickref-alpha-164) status { info } @end
  @implements(xpath-functions:quickref-alpha-165) status { info } @end
  @implements(xpath-functions:quickref-alpha-166) status { info } @end
  @implements(xpath-functions:quickref-alpha-167) status { info } @end
  @implements(xpath-functions:quickref-alpha-168) status { info } @end
  @implements(xpath-functions:quickref-alpha-169) status { info } @end
  @implements(xpath-functions:quickref-alpha-170) status { info } @end
  @implements(xpath-functions:quickref-alpha-171) status { info } @end
  @implements(xpath-functions:quickref-alpha-172) status { info } @end
  @implements(xpath-functions:quickref-alpha-173) status { info } @end
  @implements(xpath-functions:quickref-alpha-174) status { info } @end
  @implements(xpath-functions:quickref-alpha-175) status { info } @end
  @implements(xpath-functions:quickref-alpha-176) status { info } @end
  @implements(xpath-functions:quickref-alpha-177) status { info } @end
  @implements(xpath-functions:quickref-alpha-178) status { info } @end
  @implements(xpath-functions:quickref-alpha-179) status { info } @end
  @implements(xpath-functions:quickref-alpha-180) status { info } @end
  @implements(xpath-functions:quickref-alpha-181) status { info } @end
  @implements(xpath-functions:quickref-alpha-182) status { info } @end
  @implements(xpath-functions:quickref-alpha-183) status { info } @end
  @implements(xpath-functions:quickref-alpha-184) status { info } @end
  @implements(xpath-functions:quickref-alpha-185) status { info } @end
  @implements(xpath-functions:quickref-alpha-186) status { info } @end
  @implements(xpath-functions:quickref-alpha-187) status { info } @end
  @implements(xpath-functions:quickref-alpha-188) status { info } @end
  @implements(xpath-functions:quickref-alpha-189) status { info } @end
  @implements(xpath-functions:quickref-alpha-190) status { info } @end
  @implements(xpath-functions:quickref-alpha-191) status { info } @end
  @implements(xpath-functions:quickref-alpha-192) status { info } @end
  @implements(xpath-functions:quickref-alpha-193) status { info } @end
  @implements(xpath-functions:quickref-alpha-194) status { info } @end
  @implements(xpath-functions:quickref-alpha-195) status { info } @end
  @implements(xpath-functions:quickref-alpha-196) status { info } @end
  @implements(xpath-functions:quickref-alpha-197) status { info } @end
  @implements(xpath-functions:quickref-alpha-198) status { info } @end
  @implements(xpath-functions:quickref-alpha-199) status { info } @end
  @implements(xpath-functions:quickref-alpha-200) status { info } @end
  @implements(xpath-functions:quickref-alpha-201) status { info } @end
  @implements(xpath-functions:quickref-alpha-202) status { info } @end
  @implements(xpath-functions:quickref-alpha-203) status { info } @end
  @implements(xpath-functions:quickref-alpha-204) status { info } @end
  @implements(xpath-functions:quickref-alpha-205) status { info } @end
  @implements(xpath-functions:quickref-alpha-206) status { info } @end
  @implements(xpath-functions:quickref-alpha-207) status { info } @end
  @implements(xpath-functions:quickref-alpha-208) status { info } @end
  @implements(xpath-functions:quickref-alpha-209) status { info } @end
  @implements(xpath-functions:quickref-alpha-210) status { info } @end
  @implements(xpath-functions:quickref-alpha-211) status { info } @end
  @implements(xpath-functions:quickref-alpha-212) status { info } @end
  @implements(xpath-functions:quickref-alpha-213) status { info } @end
  @implements(xpath-functions:quickref-alpha-214) status { info } @end
  @implements(xpath-functions:quickref-alpha-215) status { info } @end
  @implements(xpath-functions:quickref-alpha-216) status { info } @end
  @implements(xpath-functions:quickref-alpha-217) status { info } @end

*/
